name: Task1
env:  
  DOCKER_HUB_REPONAME : dockrepo_1
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  DockerImageCICD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for service1
      run: docker build . --file src/Service1/Dockerfile --tag ${{secrets.DOCKER_HUB_USERNAME}}/${{env.DOCKER_HUB_REPONAME}}:serviceimage1
      
    - name: Build the Docker image for service2
      run: docker build . --file src/Service2/Dockerfile --tag ${{secrets.DOCKER_HUB_USERNAME}}/${{env.DOCKER_HUB_REPONAME}}:serviceimage2

    - name: Login to DockerHub 
      run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}} docker.io
   
    - name: Push to Docker Hub
      run: docker image push ${{secrets.DOCKER_HUB_USERNAME}}/${{env.DOCKER_HUB_REPONAME}}:serviceimage1
      
    - name: Push to Docker Hub
      run: docker image push ${{secrets.DOCKER_HUB_USERNAME}}/${{env.DOCKER_HUB_REPONAME}}:serviceimage2
