name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101    

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Service1.UnitTests
      run: dotnet test src/Service1.UnitTests --no-restore --verbosity minimal
       
 #   - name: Service2.UnitTests
 #     run: dotnet test src/Service2.UnitTests --no-restore --verbosity minimal

    - name: Publish All
      run: dotnet publish

    - name: Upload Service1.UnitTests Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Service1.UnitTests
        path: /home/runner/work/Devops/Devops/src/Service1.UnitTests/bin/Release/netcoreapp3.1/publish/
